/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_andresmoncada;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Dell
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        initListas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_signin = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        signin_email = new javax.swing.JTextField();
        signin_pass = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jd_login = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cu_email = new javax.swing.JTextField();
        cu_pass = new javax.swing.JPasswordField();
        cu_dob = new com.toedter.calendar.JDateChooser();
        cu_tarjeta = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jd_cs = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cs_id = new javax.swing.JTextField();
        cs_nom = new javax.swing.JTextField();
        cs_temp = new javax.swing.JSpinner();
        cs_rat = new javax.swing.JSpinner();
        cs_pr = new javax.swing.JTextField();
        cs_dir = new javax.swing.JTextField();
        cs_h = new javax.swing.JSpinner();
        cs_min = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        cs_cat = new javax.swing.JTextField();
        jd_cp = new javax.swing.JDialog();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cp_id = new javax.swing.JTextField();
        cp_nom = new javax.swing.JTextField();
        cp_cat = new javax.swing.JTextField();
        cp_rat = new javax.swing.JSpinner();
        cp_pr = new javax.swing.JTextField();
        cp_dir = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        cp_h = new javax.swing.JSpinner();
        jLabel39 = new javax.swing.JLabel();
        cp_min = new javax.swing.JSpinner();
        jLabel40 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jd_ms = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        ms_id = new javax.swing.JTextField();
        ms_nom = new javax.swing.JTextField();
        ms_temp = new javax.swing.JSpinner();
        ms_rat = new javax.swing.JSpinner();
        ms_pr = new javax.swing.JTextField();
        ms_dir = new javax.swing.JTextField();
        ms_h = new javax.swing.JSpinner();
        ms_min = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        ms_cat = new javax.swing.JTextField();
        jd_mp = new javax.swing.JDialog();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        mp_id = new javax.swing.JTextField();
        mp_nom = new javax.swing.JTextField();
        mp_cat = new javax.swing.JTextField();
        mp_rat = new javax.swing.JSpinner();
        mp_pr = new javax.swing.JTextField();
        mp_dir = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        mp_h = new javax.swing.JSpinner();
        jLabel48 = new javax.swing.JLabel();
        mp_min = new javax.swing.JSpinner();
        jLabel49 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_series = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_peliculas = new javax.swing.JList<>();
        add_s = new javax.swing.JButton();
        add_p = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_sesion = new javax.swing.JMenu();
        jmi_signin = new javax.swing.JMenuItem();
        jmi_login = new javax.swing.JMenuItem();
        jmi_signout = new javax.swing.JMenuItem();
        jm_admin = new javax.swing.JMenu();
        jmi_cs = new javax.swing.JMenuItem();
        jmi_ms = new javax.swing.JMenuItem();
        jmi_es = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmi_cp = new javax.swing.JMenuItem();
        jmi_mp = new javax.swing.JMenuItem();
        jmi_ep = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel4.setText("Correo");

        jLabel5.setText("Contraseña");

        jButton3.setText("Iniciar sesión");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_signinLayout = new javax.swing.GroupLayout(jd_signin.getContentPane());
        jd_signin.getContentPane().setLayout(jd_signinLayout);
        jd_signinLayout.setHorizontalGroup(
            jd_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signinLayout.createSequentialGroup()
                .addGroup(jd_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_signinLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jd_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jd_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(signin_email)
                            .addComponent(signin_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))
                    .addGroup(jd_signinLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton3)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jd_signinLayout.setVerticalGroup(
            jd_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signinLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jd_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(signin_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jd_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(signin_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton3)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel25.setText("Email");

        jLabel26.setText("Contraseña");

        jLabel27.setText("Fecha de nacimiento");

        jLabel28.setText("Tarjeta de credito");

        jButton4.setText("Crear cuenta");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel29.setText("*Usamos tu tarjeta de crédito para verificar tu identidad");

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addGroup(jd_loginLayout.createSequentialGroup()
                                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cu_email)
                                    .addComponent(cu_pass)
                                    .addComponent(cu_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cu_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButton4)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cu_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cu_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(cu_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(cu_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addGap(26, 26, 26)
                .addComponent(jButton4)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel7.setText("ID");

        jLabel8.setText("Temporadas");

        jLabel9.setText("Nombre");

        jLabel10.setText("Duracion");

        jLabel11.setText("Rating");

        jLabel12.setText("Productora");

        jLabel13.setText("Director");

        cs_temp.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        cs_rat.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        cs_h.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        cs_min.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel14.setText("H");

        jLabel15.setText("min");

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel30.setText("Categoría");

        javax.swing.GroupLayout jd_csLayout = new javax.swing.GroupLayout(jd_cs.getContentPane());
        jd_cs.getContentPane().setLayout(jd_csLayout);
        jd_csLayout.setHorizontalGroup(
            jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_csLayout.createSequentialGroup()
                .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_csLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)))
                        .addGroup(jd_csLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel8)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)))))
                .addGap(18, 18, 18)
                .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_csLayout.createSequentialGroup()
                        .addComponent(cs_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(10, 10, 10)
                        .addComponent(cs_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel15)
                        .addGap(154, 154, 154)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cs_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jd_csLayout.createSequentialGroup()
                            .addComponent(cs_temp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(jLabel30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cs_cat))
                        .addComponent(cs_rat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cs_dir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(cs_pr, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(cs_id, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jd_csLayout.setVerticalGroup(
            jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_csLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cs_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cs_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_csLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cs_temp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cs_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cs_rat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cs_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(cs_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cs_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(cs_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_csLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel32.setText("ID");

        jLabel33.setText("Nombre");

        jLabel34.setText("Categoría");

        jLabel35.setText("Rating");

        jLabel36.setText("Productora");

        jLabel37.setText("Director");

        cp_rat.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jLabel38.setText("Duración");

        cp_h.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel39.setText("H");

        cp_min.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel40.setText("min");

        jButton5.setText("Crear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_cpLayout = new javax.swing.GroupLayout(jd_cp.getContentPane());
        jd_cp.getContentPane().setLayout(jd_cpLayout);
        jd_cpLayout.setHorizontalGroup(
            jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_cpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jLabel35)
                    .addComponent(jLabel32)
                    .addComponent(jLabel36)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_cpLayout.createSequentialGroup()
                        .addGroup(jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_cpLayout.createSequentialGroup()
                                    .addComponent(cp_rat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel34)
                                    .addGap(18, 18, 18)
                                    .addComponent(cp_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cp_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cp_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cp_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(jd_cpLayout.createSequentialGroup()
                        .addComponent(cp_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cp_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jd_cpLayout.setVerticalGroup(
            jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_cpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(cp_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(cp_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34)
                    .addComponent(cp_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cp_rat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(cp_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(cp_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_cpLayout.createSequentialGroup()
                        .addGroup(jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addGroup(jd_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cp_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel39)
                                .addComponent(cp_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel40)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel16.setText("ID");

        jLabel17.setText("Temporadas");

        jLabel18.setText("Nombre");

        jLabel19.setText("Duracion");

        jLabel20.setText("Rating");

        jLabel21.setText("Productora");

        jLabel22.setText("Director");

        ms_temp.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        ms_rat.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        ms_h.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        ms_min.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel23.setText("H");

        jLabel24.setText("min");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel31.setText("Categoría");

        javax.swing.GroupLayout jd_msLayout = new javax.swing.GroupLayout(jd_ms.getContentPane());
        jd_ms.getContentPane().setLayout(jd_msLayout);
        jd_msLayout.setHorizontalGroup(
            jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_msLayout.createSequentialGroup()
                .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_msLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel16)))
                        .addGroup(jd_msLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel17)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)))))
                .addGap(18, 18, 18)
                .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_msLayout.createSequentialGroup()
                        .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ms_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_msLayout.createSequentialGroup()
                                .addComponent(ms_temp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel31)
                                .addGap(18, 18, 18)
                                .addComponent(ms_cat))
                            .addComponent(ms_rat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ms_dir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(ms_pr, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(ms_id, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(jd_msLayout.createSequentialGroup()
                        .addComponent(ms_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(10, 10, 10)
                        .addComponent(ms_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jd_msLayout.setVerticalGroup(
            jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_msLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ms_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ms_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ms_temp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(ms_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(ms_rat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ms_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(ms_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_msLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ms_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(ms_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel41.setText("ID");

        jLabel42.setText("Nombre");

        jLabel43.setText("Categoría");

        jLabel44.setText("Rating");

        jLabel45.setText("Productora");

        jLabel46.setText("Director");

        mp_rat.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jLabel47.setText("Duración");

        mp_h.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel48.setText("H");

        mp_min.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel49.setText("min");

        jButton6.setText("Modificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_mpLayout = new javax.swing.GroupLayout(jd_mp.getContentPane());
        jd_mp.getContentPane().setLayout(jd_mpLayout);
        jd_mpLayout.setHorizontalGroup(
            jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel47)
                    .addComponent(jLabel46)
                    .addComponent(jLabel44)
                    .addComponent(jLabel41)
                    .addComponent(jLabel45)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mpLayout.createSequentialGroup()
                        .addGroup(jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mpLayout.createSequentialGroup()
                                    .addComponent(mp_rat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel43)
                                    .addGap(18, 18, 18)
                                    .addComponent(mp_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(mp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mp_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mp_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mp_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(jd_mpLayout.createSequentialGroup()
                        .addComponent(mp_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mp_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jd_mpLayout.setVerticalGroup(
            jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(mp_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(mp_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel43)
                    .addComponent(mp_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mp_rat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(mp_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(mp_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addGroup(jd_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mp_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel48)
                        .addComponent(mp_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categorías");
        tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(tree);

        jl_series.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_series);

        jl_peliculas.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_peliculas);

        add_s.setText("Agregar Serie");
        add_s.setEnabled(false);
        add_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_sActionPerformed(evt);
            }
        });

        add_p.setText("Agregar Película");
        add_p.setEnabled(false);
        add_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_pActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Favoritos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Series");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Películas");

        jLabel6.setText("Para guardar informacion de usuarios seleccione la opción \"Guardar Datos\" como administrador");

        jm_sesion.setText("Sesión");

        jmi_signin.setText("Sign in");
        jmi_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_signinActionPerformed(evt);
            }
        });
        jm_sesion.add(jmi_signin);

        jmi_login.setText("Log in");
        jmi_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_loginActionPerformed(evt);
            }
        });
        jm_sesion.add(jmi_login);

        jmi_signout.setText("Sign out");
        jmi_signout.setEnabled(false);
        jmi_signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_signoutActionPerformed(evt);
            }
        });
        jm_sesion.add(jmi_signout);

        jMenuBar1.add(jm_sesion);

        jm_admin.setText("Administrador");
        jm_admin.setEnabled(false);

        jmi_cs.setText("Crear Serie");
        jmi_cs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_csActionPerformed(evt);
            }
        });
        jm_admin.add(jmi_cs);

        jmi_ms.setText("Modificar Serie");
        jmi_ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_msActionPerformed(evt);
            }
        });
        jm_admin.add(jmi_ms);

        jmi_es.setText("Eliminar Serie");
        jmi_es.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_esActionPerformed(evt);
            }
        });
        jm_admin.add(jmi_es);
        jm_admin.add(jSeparator1);

        jmi_cp.setText("Crear Película");
        jmi_cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cpActionPerformed(evt);
            }
        });
        jm_admin.add(jmi_cp);

        jmi_mp.setText("Modificar Película");
        jmi_mp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mpActionPerformed(evt);
            }
        });
        jm_admin.add(jmi_mp);

        jmi_ep.setText("Eliminar Película");
        jmi_ep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_epActionPerformed(evt);
            }
        });
        jm_admin.add(jmi_ep);
        jm_admin.add(jSeparator2);

        jMenuItem1.setText("Guardar Datos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jm_admin.add(jMenuItem1);

        jMenuBar1.add(jm_admin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(197, 197, 197))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(add_s))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(add_p))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel3)))
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel6)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_p)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add_s)
                                .addGap(114, 114, 114)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initListas(){
        usuarios.add(new Usuario("test", "test", new Date(), "AAAA"));
        Serie s = new Serie(2, 1, "Animaniacs", "Comedia", 3, "WB", "Steven Spielberg", "00:22");
        s.getIdiomas().add("Ingles");
        s.getSubt().add("Ingles");
        s.getSubt().add("Español");
        series.add(s);
        s = new Serie(1, 2, "Harry Potter y la Serie que Arruino la Continuidad", "Romance", 4, "ABC", "Christopher Nolan", "1:30");
        s.getIdiomas().add("Ingles");
        s.getIdiomas().add("Español");
        s.getSubt().add("Ingles");
        s.getSubt().add("Español");
        s.getSubt().add("Frances");
        series.add(s);
        s = new Serie(3, 3, "Whinnie the Pooh: La Historia Detras del Libro", "Suspenso", 5, "NBC", "Gullermo del Toro", "00:15");
        s.getIdiomas().add("Ingles");
        s.getIdiomas().add("Español");
        s.getIdiomas().add("Frances");
        s.getSubt().add("Ingles");
        s.getSubt().add("Español");
        s.getSubt().add("Frances");
        s.getSubt().add("Ruso");
        series.add(s);
        s = new Serie(2, 4, "Accidentes Marinos", "Deporte", 1, "FOX", "Edgar Wright", "00:25");
        s.getIdiomas().add("Ingles");
        s.getIdiomas().add("Español");
        s.getIdiomas().add("Frances");
        s.getIdiomas().add("Ruso");
        s.getSubt().add("Ingles");
        s.getSubt().add("Español");
        s.getSubt().add("Frances");
        s.getSubt().add("Ruso");
        series.add(s);
        s = new Serie(6, 5, "Star Wars Episodio 1", "Terror", 2, "Disney", "George Lucas", "00:20");
        s.getIdiomas().add("Ingles");
        s.getIdiomas().add("Español");
        s.getIdiomas().add("Frances");
        s.getIdiomas().add("Ruso");
        s.getSubt().add("Ingles");
        s.getSubt().add("Español");
        s.getSubt().add("Frances");
        s.getSubt().add("Ruso");
        series.add(s);
        s = new Serie(3, 6, "Noticias de Ultima Hora", "Comedia", 3, "HBO", "Peter Jackson", "00:45");
        s.getIdiomas().add("Ingles");
        s.getIdiomas().add("Español");
        s.getIdiomas().add("Frances");
        s.getIdiomas().add("Ruso");
        s.getSubt().add("Ingles");
        s.getSubt().add("Español");
        s.getSubt().add("Frances");
        s.getSubt().add("Ruso");
        series.add(s);
        s = new Serie(4, 7, "La Cucaracha", "Drama", 4, "Canal 5", "Ang Lee", "00:59");
        s.getIdiomas().add("Ingles");
        s.getIdiomas().add("Español");
        s.getIdiomas().add("Frances");
        s.getIdiomas().add("Ruso");
        s.getSubt().add("Ingles");
        s.getSubt().add("Español");
        s.getSubt().add("Frances");
        s.getSubt().add("Ruso");
        series.add(s);
        s = new Serie(2, 8, "Volleyball Navideño", "Deporte", 5, "ESPN", "Woody Allen", "01:04");
        s.getIdiomas().add("Ingles");
        s.getIdiomas().add("Español");
        s.getIdiomas().add("Frances");
        s.getIdiomas().add("Ruso");
        s.getSubt().add("Ingles");
        s.getSubt().add("Español");
        s.getSubt().add("Frances");
        s.getSubt().add("Ruso");
        series.add(s);
        s = new Serie(5, 9, "Comida, la Serie", "Suspenso", 4, "Cartoon Network", "M. Night Shyamalan", "02:00");
        s.getIdiomas().add("Ingles");
        s.getIdiomas().add("Español");
        s.getIdiomas().add("Frances");
        s.getIdiomas().add("Ruso");
        s.getSubt().add("Ingles");
        s.getSubt().add("Español");
        s.getSubt().add("Frances");
        s.getSubt().add("Ruso");
        series.add(s);
        s = new Serie(1, 10, "Novela Mexicana", "Drama", 5, "Telemundo", "Brad Bird", "00:10");
        s.getIdiomas().add("Aleman");
        s.getSubt().add("Esperanto");
        series.add(s);
        Pelicula p = new Pelicula(101, "Sharknado", "Romance", 1, "Marvel", "Stanley Kubrick", "03:00");
        p.getIdiomas().add("Ingles");
        p.getIdiomas().add("Español");
        p.getIdiomas().add("Frances");
        p.getIdiomas().add("Ruso");
        p.getSubt().add("Ingles");
        p.getSubt().add("Español");
        p.getSubt().add("Frances");
        p.getSubt().add("Ruso");
        peliculas.add(p);
        p = new Pelicula(102, "Sharknado 2", "Drama", 1, "Disney", "Martin Scorsese", "01:20");
        p.getIdiomas().add("Ingles");
        p.getIdiomas().add("Español");
        p.getIdiomas().add("Frances");
        p.getIdiomas().add("Ruso");
        p.getSubt().add("Ingles");
        p.getSubt().add("Español");
        p.getSubt().add("Frances");
        p.getSubt().add("Ruso");
        peliculas.add(p);
        p = new Pelicula(103, "Sharknado 3", "Accion", 1, "FOX", "Alfred Hitchcock", "01:12");
        p.getIdiomas().add("Ingles");
        p.getIdiomas().add("Español");
        p.getIdiomas().add("Frances");
        p.getIdiomas().add("Ruso");
        p.getSubt().add("Ingles");
        p.getSubt().add("Español");
        p.getSubt().add("Frances");
        p.getSubt().add("Ruso");
        peliculas.add(p);
        p = new Pelicula(104, "Sharknado 4", "Comedia", 1, "Ilumination", "Roman Polanski", "01:30");
        p.getIdiomas().add("Ingles");
        p.getIdiomas().add("Español");
        p.getIdiomas().add("Frances");
        p.getIdiomas().add("Ruso");
        p.getSubt().add("Ingles");
        p.getSubt().add("Español");
        p.getSubt().add("Frances");
        p.getSubt().add("Ruso");
        peliculas.add(p);
        p = new Pelicula(105, "Sharknado 5", "Suspenso", 1, "Blue Sky", "Ridley Scott", "02:15");
        p.getIdiomas().add("Ingles");
        p.getIdiomas().add("Español");
        p.getIdiomas().add("Frances");
        p.getIdiomas().add("Ruso");
        p.getSubt().add("Ingles");
        p.getSubt().add("Español");
        p.getSubt().add("Frances");
        p.getSubt().add("Ruso");
        peliculas.add(p);
        p = new Pelicula(106, "The Room", "Accion", 2, "Pixar", "James Cameron", "02:17");
        p.getIdiomas().add("Ingles");
        p.getIdiomas().add("Español");
        p.getIdiomas().add("Frances");
        p.getIdiomas().add("Ruso");
        p.getSubt().add("Ingles");
        p.getSubt().add("Español");
        p.getSubt().add("Frances");
        p.getSubt().add("Ruso");
        peliculas.add(p);
        p = new Pelicula(107, "Camida, La Serie, La Pelicula", "Deporte", 5, "Disney", "Quentin Tarantino", "00:45");
        p.getIdiomas().add("Ingles");
        p.getIdiomas().add("Español");
        p.getIdiomas().add("Frances");
        p.getIdiomas().add("Ruso");
        p.getSubt().add("Ingles");
        p.getSubt().add("Español");
        p.getSubt().add("Frances");
        p.getSubt().add("Ruso");
        peliculas.add(p);
        p = new Pelicula(108, "Comedia Generica", "Terror", 3, "Sony Pictures", "Francis Ford Copola", "01:00");
        p.getIdiomas().add("Ingles");
        p.getIdiomas().add("Español");
        p.getIdiomas().add("Frances");
        p.getIdiomas().add("Ruso");
        p.getSubt().add("Ingles");
        p.getSubt().add("Español");
        p.getSubt().add("Frances");
        p.getSubt().add("Ruso");
        peliculas.add(p);
        p = new Pelicula(109, "Citizen Kane 2", "Romance", 5, "Guacamaya Films", "Joel Coen", "02:00");
        p.getIdiomas().add("Español");
        p.getSubt().add("Ruso");
        peliculas.add(p);
        p = new Pelicula(110, "La Histora de las Tortillas con Quesillo", "Documental", 1, "Dreamworks", "Ron Howard", "02:26");
        p.getIdiomas().add("Ingles");
        p.getIdiomas().add("Español");
        p.getIdiomas().add("Frances");
        p.getIdiomas().add("Ruso");
        p.getSubt().add("Ingles");
        p.getSubt().add("Español");
        p.getSubt().add("Frances");
        p.getSubt().add("Ruso");
        peliculas.add(p);
        DefaultListModel ms = (DefaultListModel)jl_series.getModel();
        DefaultListModel mp = (DefaultListModel)jl_peliculas.getModel();
        for (Serie se : series) {
            ms.addElement(se);
        }
        for (Pelicula peli : peliculas) {
            mp.addElement(peli);
        }
    }

    private void jmi_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_signinActionPerformed
        jd_signin.setModal(true);
        jd_signin.pack();
        jd_signin.setLocationRelativeTo(this);
        jd_signin.setVisible(true);
    }//GEN-LAST:event_jmi_signinActionPerformed

    private void jmi_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_loginActionPerformed
        jd_login.setModal(true);
        jd_login.pack();
        jd_login.setLocationRelativeTo(this);
        jd_login.setVisible(true);
    }//GEN-LAST:event_jmi_loginActionPerformed

    private void jmi_signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_signoutActionPerformed
        jm_admin.setEnabled(false);
        jmi_signin.setEnabled(true);
        jmi_login.setEnabled(true);
        add_s.setEnabled(false);
        add_p.setEnabled(false);
        jmi_signout.setEnabled(false);
        tree.setModel(new DefaultTreeModel(new DefaultMutableTreeNode("Categorias")));
    }//GEN-LAST:event_jmi_signoutActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean v;
        if(signin_pass.getText().equals("admin")&& signin_email.getText().equals("admin")){
            signin_pass.setText("");
            signin_email.setText("");
            jd_signin.setVisible(false);
            jmi_signin.setEnabled(false);
            jmi_signout.setEnabled(true);
            jmi_login.setEnabled(false);
            jm_admin.setEnabled(true);
        }else{
            v = false;
            for (int i = 0; i < usuarios.size(); i++) {
                if (signin_pass.getText().equals(usuarios.get(i).getPass())&& signin_email.getText().equals(usuarios.get(i).getEmail())){
                    signin_pass.setText("");
                    signin_email.setText("");
                    v = true;
                    index_u = i;
                    tree.setModel(usuarios.get(index_u).getArbol());
                    break;
                }
            }
            if(v){
                jd_signin.setVisible(false);
                jm_admin.setEnabled(false);
                jmi_signin.setEnabled(false);
                jmi_login.setEnabled(false);
                add_s.setEnabled(true);
                add_p.setEnabled(true);
                jmi_signout.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(jd_signin, "Usuario o contraseña incorrectos");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void add_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_sActionPerformed
        if(jl_series.getSelectedIndex() >= 0){
            DefaultTreeModel tm = (DefaultTreeModel)tree.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)tm.getRoot();
            DefaultListModel lm = (DefaultListModel)jl_series.getModel();
            DefaultMutableTreeNode nodo = new DefaultMutableTreeNode((Serie)lm.get(jl_series.getSelectedIndex()));
            String categoria = ((Serie)lm.get(jl_series.getSelectedIndex())).getCat();
            String nombre = ((Serie)lm.get(jl_series.getSelectedIndex())).getNombre();
            int c = 0;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if(categoria.equals(raiz.getChildAt(i).toString())){
                    for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                        if(nombre.equals(raiz.getChildAt(i).getChildAt(j).toString())){
                            c = 1;
                            JOptionPane.showMessageDialog(this, "Ya agrego esta serie");
                            break;
                        }
                    }
                    if (c != 1){
                        ((DefaultMutableTreeNode)raiz.getChildAt(i)).add(nodo);
                        c = 2;
                        usuarios.get(index_u).getFavoritos().add((Serie)lm.get(jl_series.getSelectedIndex()));
                        break;
                    }
                }         
            }//fin for
            if (c == 0){
                DefaultMutableTreeNode cat = new DefaultMutableTreeNode(categoria);
                cat.add(nodo);
                raiz.add(cat);
                usuarios.get(index_u).getFavoritos().add((Serie)lm.get(jl_series.getSelectedIndex()));
            }
            tm.reload();
            usuarios.get(index_u).setArbol(tm);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una serie primero");
        }
    }//GEN-LAST:event_add_sActionPerformed

    private void add_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_pActionPerformed
        if(jl_peliculas.getSelectedIndex() >= 0){
            DefaultTreeModel tm = (DefaultTreeModel)tree.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)tm.getRoot();
            DefaultListModel lm = (DefaultListModel)jl_peliculas.getModel();
            DefaultMutableTreeNode nodo = new DefaultMutableTreeNode((Pelicula)lm.get(jl_peliculas.getSelectedIndex()));
            String categoria = ((Pelicula)lm.get(jl_peliculas.getSelectedIndex())).getCat();
            String nombre = ((Pelicula)lm.get(jl_peliculas.getSelectedIndex())).getNombre();
            int c = 0;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if(categoria.equals(raiz.getChildAt(i).toString())){
                    for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                        if(nombre.equals(raiz.getChildAt(i).getChildAt(j).toString())){
                            c = 1;
                            JOptionPane.showMessageDialog(this, "Ya agrego esta pelicula");
                            break;
                        }
                    }
                    if (c != 1){
                        ((DefaultMutableTreeNode)raiz.getChildAt(i)).add(nodo);
                        c = 2;
                        usuarios.get(index_u).getFavoritos().add((Pelicula)lm.get(jl_peliculas.getSelectedIndex()));
                        break;
                    }
                }         
            }//fin for
            if (c == 0){
                DefaultMutableTreeNode cat = new DefaultMutableTreeNode(categoria);
                cat.add(nodo);
                raiz.add(cat);
                usuarios.get(index_u).getFavoritos().add((Pelicula)lm.get(jl_peliculas.getSelectedIndex()));
            }
            tm.reload();
            usuarios.get(index_u).setArbol(tm);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una pelicula primero");
        }
    }//GEN-LAST:event_add_pActionPerformed

    private void jmi_csActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_csActionPerformed
        jd_cs.setModal(true);
        jd_cs.setLocationRelativeTo(this);
        jd_cs.pack();
        jd_cs.setVisible(true);
    }//GEN-LAST:event_jmi_csActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            int id = Integer.parseInt(cs_id.getText());
            boolean v = true;
            for (Serie se : series) {
                if(se.getId() == id){
                    v = false;
                    break;
                }
            }
            for (Pelicula peli : peliculas) {
                if(peli.getId() == id){
                    v = false;
                    break;
                }
            }
            if(v){
                String h;
                if((int)cs_h.getValue() >= 10)
                    h = cs_h.getValue().toString();
                else
                    h = "0" + cs_h.getValue();
                String m;
                if((int)cs_min.getValue() >= 10)
                    m = cs_min.getValue().toString();
                else
                    m = "0" + cs_min.getValue();
                String d = h + ":" + m;
                series.add(new Serie((int)cs_temp.getValue(),id,cs_nom.getText(),cs_cat.getText(),
                        (int)cs_rat.getValue(),cs_pr.getText(),cs_dir.getText(),d));
                DefaultListModel lm = (DefaultListModel) jl_series.getModel();
                lm.addElement(series.get(series.size()-1));
                jd_cs.setVisible(false);
                cs_temp.setValue(1);
                cs_id.setText("");
                cs_nom.setText("");
                cs_cat.setText("");
                cs_dir.setText("");
                cs_h.setValue(0);
                cs_min.setValue(0);
                cs_pr.setText("");
                cs_rat.setValue(1);
            }else
                JOptionPane.showMessageDialog(this, "Ya existe una serie/pelicula con esta ID");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Se produjo un error al agregar la serie");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int id = Integer.parseInt(ms_id.getText());
            boolean v = true;
            DefaultListModel lm = (DefaultListModel) jl_series.getModel();
            if(jl_series.getSelectedIndex() >= 0){
                for (Serie se : series) {
                    if(se.getId() == id){
                        v = false;
                        break;
                    }
                }
                for (Pelicula peli : peliculas) {
                    if(peli.getId() == id){
                        v = false;
                        break;
                    }
                }
                if(v){
                    String h;
                    if((int)ms_h.getValue() >= 10)
                        h = ms_h.getValue().toString();
                    else
                        h = "0" + ms_h.getValue();
                    String m;
                    if((int)ms_min.getValue() >= 10)
                        m = ms_min.getValue().toString();
                    else
                        m = "0" + ms_min.getValue();
                    String d = h + ":" + m;
                    series.get(jl_series.getSelectedIndex()).setCat(ms_cat.getText());
                    series.get(jl_series.getSelectedIndex()).setDirector(ms_dir.getText());
                    series.get(jl_series.getSelectedIndex()).setDuracion(d);
                    series.get(jl_series.getSelectedIndex()).setId(id);
                    series.get(jl_series.getSelectedIndex()).setNombre(ms_nom.getText());
                    series.get(jl_series.getSelectedIndex()).setProductora(ms_pr.getText());
                    series.get(jl_series.getSelectedIndex()).setRating((int)ms_rat.getValue());
                    series.get(jl_series.getSelectedIndex()).setTemporadas((int)ms_temp.getValue());
                    lm.set(jl_series.getSelectedIndex(),series.get(jl_series.getSelectedIndex()));
                    jd_ms.setVisible(false);
                    ms_temp.setValue(1);
                    ms_id.setText("");
                    ms_nom.setText("");
                    ms_cat.setText("");
                    ms_dir.setText("");
                    ms_h.setValue(0);
                    ms_min.setValue(0);
                    ms_pr.setText("");
                    ms_rat.setValue(1);
                }else
                    JOptionPane.showMessageDialog(this, "Ya existe una serie/pelicula con esta ID");
            }else
                JOptionPane.showMessageDialog(this, "Seleccione una serie primero");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Se produjo un error al modificar la serie");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmi_msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_msActionPerformed
        jd_ms.setModal(true);
        jd_ms.setLocationRelativeTo(this);
        jd_ms.pack();
        jd_ms.setVisible(true);
    }//GEN-LAST:event_jmi_msActionPerformed

    private void jmi_esActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_esActionPerformed
        DefaultListModel lm = (DefaultListModel) jl_series.getModel();
        if(jl_series.getSelectedIndex() >= 0){
            int s = JOptionPane.showConfirmDialog(this, "Eliminar " +((Serie)lm.getElementAt(jl_series.getSelectedIndex())).toString()+"?","Eliminar Serie", JOptionPane.OK_CANCEL_OPTION);
            if (s == JOptionPane.OK_OPTION){
                lm.remove(jl_series.getSelectedIndex());
                series.remove(jl_series.getSelectedIndex());
            }
        }else
            JOptionPane.showMessageDialog(this, "Seleccione una serie primero");
    }//GEN-LAST:event_jmi_esActionPerformed

    private void jmi_cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cpActionPerformed
        jd_cp.setModal(true);
        jd_cp.pack();
        jd_cp.setLocationRelativeTo(this);
        jd_cp.setVisible(true);
    }//GEN-LAST:event_jmi_cpActionPerformed

    private void jmi_mpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mpActionPerformed
        jd_mp.setModal(true);
        jd_mp.pack();
        jd_mp.setLocationRelativeTo(this);
        jd_mp.setVisible(true);
    }//GEN-LAST:event_jmi_mpActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            usuarios.add(new Usuario(cu_email.getText(),cu_pass.getText(),cu_dob.getDate(),cu_tarjeta.getText()));
            jd_login.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Se produjo un error al crear usuario");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jmi_epActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_epActionPerformed
        DefaultListModel lm = (DefaultListModel) jl_peliculas.getModel();
        if(jl_peliculas.getSelectedIndex() >= 0){
            int s = JOptionPane.showConfirmDialog(this, "Eliminar " +((Pelicula)lm.getElementAt(jl_peliculas.getSelectedIndex())).toString()+"?","Eliminar Serie", JOptionPane.OK_CANCEL_OPTION);
            if (s == JOptionPane.OK_OPTION){
                lm.remove(jl_peliculas.getSelectedIndex());
                peliculas.remove(jl_peliculas.getSelectedIndex());
            }
        }else
            JOptionPane.showMessageDialog(this, "Seleccione una película primero");
    }//GEN-LAST:event_jmi_epActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            archivo = new File("./Informacion Usuarios");
            fw = new FileWriter(archivo, false);
            bw = new BufferedWriter(fw);
            for (Usuario u : usuarios) {
                bw.write(u.getEmail() + "; ");
                for (int i = 0; i < u.getFavoritos().size(); i++) {
                    bw.write(u.getFavoritos().get(i).datos() + ", ");
                }
                bw.write(";");
                bw.newLine();
            }
            JOptionPane.showMessageDialog(this, "Datos guardados en archivo \"Informacion de Usuarios\"");
        } catch (Exception e) {
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException e) {
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try{
            int id = Integer.parseInt(cp_id.getText());
            boolean v = true;
            for (Serie se : series) {
                if(se.getId() == id){
                    v = false;
                    break;
                }
            }
            for (Pelicula peli : peliculas) {
                if(peli.getId() == id){
                    v = false;
                    break;
                }
            }
            if(v){
                String h;
                if((int)cp_h.getValue() >= 10)
                    h = cp_h.getValue().toString();
                else
                    h = "0" + cp_h.getValue();
                String m;
                if((int)cp_min.getValue() >= 10)
                    m = cp_min.getValue().toString();
                else
                    m = "0" + cp_min.getValue();
                String d = h + ":" + m;
                peliculas.add(new Pelicula(id,cp_nom.getText(),cp_cat.getText(),
                        (int)cp_rat.getValue(),cp_pr.getText(),cp_dir.getText(),d));
                DefaultListModel lm = (DefaultListModel) jl_peliculas.getModel();
                lm.addElement(peliculas.get(peliculas.size()-1));
                jd_cp.setVisible(false);
                cp_id.setText("");
                cp_nom.setText("");
                cp_cat.setText("");
                cp_dir.setText("");
                cp_h.setValue(0);
                cp_min.setValue(0);
                cp_pr.setText("");
                cp_rat.setValue(1);
            }else
                JOptionPane.showMessageDialog(this, "Ya existe una serie/pelicula con esta ID");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Se produjo un error al agregar la pelicula");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            int id = Integer.parseInt(mp_id.getText());
            boolean v = true;
            DefaultListModel lm = (DefaultListModel) jl_peliculas.getModel();
            if(jl_peliculas.getSelectedIndex() >= 0){
                for (Serie se : series) {
                    if(se.getId() == id){
                        v = false;
                        break;
                    }
                }
                for (Pelicula peli : peliculas) {
                    if(peli.getId() == id){
                        v = false;
                        break;
                    }
                }
                if(v){
                    String h;
                    if((int)mp_h.getValue() >= 10)
                        h = mp_h.getValue().toString();
                    else
                        h = "0" + mp_h.getValue();
                    String m;
                    if((int)mp_min.getValue() >= 10)
                        m = mp_min.getValue().toString();
                    else
                        m = "0" + mp_min.getValue();
                    String d = h + ":" + m;
                    peliculas.get(jl_peliculas.getSelectedIndex()).setCat(mp_cat.getText());
                    peliculas.get(jl_peliculas.getSelectedIndex()).setDirector(mp_dir.getText());
                    peliculas.get(jl_peliculas.getSelectedIndex()).setDuracion(d);
                    peliculas.get(jl_peliculas.getSelectedIndex()).setId(id);
                    peliculas.get(jl_peliculas.getSelectedIndex()).setNombre(mp_nom.getText());
                    peliculas.get(jl_peliculas.getSelectedIndex()).setProductora(mp_pr.getText());
                    peliculas.get(jl_peliculas.getSelectedIndex()).setRating((int)mp_rat.getValue());
                    lm.set(jl_peliculas.getSelectedIndex(),peliculas.get(jl_peliculas.getSelectedIndex()));
                    jd_mp.setVisible(false);
                    mp_id.setText("");
                    mp_nom.setText("");
                    mp_cat.setText("");
                    mp_dir.setText("");
                    mp_h.setValue(0);
                    mp_min.setValue(0);
                    mp_pr.setText("");
                    mp_rat.setValue(1);
                }else
                    JOptionPane.showMessageDialog(this, "Ya existe una serie/pelicula con esta ID");
            }else
                JOptionPane.showMessageDialog(this, "Seleccione una pelicula primero");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Se produjo un error al modificar la pelicula");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_p;
    private javax.swing.JButton add_s;
    private javax.swing.JTextField cp_cat;
    private javax.swing.JTextField cp_dir;
    private javax.swing.JSpinner cp_h;
    private javax.swing.JTextField cp_id;
    private javax.swing.JSpinner cp_min;
    private javax.swing.JTextField cp_nom;
    private javax.swing.JTextField cp_pr;
    private javax.swing.JSpinner cp_rat;
    private javax.swing.JTextField cs_cat;
    private javax.swing.JTextField cs_dir;
    private javax.swing.JSpinner cs_h;
    private javax.swing.JTextField cs_id;
    private javax.swing.JSpinner cs_min;
    private javax.swing.JTextField cs_nom;
    private javax.swing.JTextField cs_pr;
    private javax.swing.JSpinner cs_rat;
    private javax.swing.JSpinner cs_temp;
    private com.toedter.calendar.JDateChooser cu_dob;
    private javax.swing.JTextField cu_email;
    private javax.swing.JPasswordField cu_pass;
    private javax.swing.JTextField cu_tarjeta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JDialog jd_cp;
    private javax.swing.JDialog jd_cs;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_mp;
    private javax.swing.JDialog jd_ms;
    private javax.swing.JDialog jd_signin;
    private javax.swing.JList<String> jl_peliculas;
    private javax.swing.JList<String> jl_series;
    private javax.swing.JMenu jm_admin;
    private javax.swing.JMenu jm_sesion;
    private javax.swing.JMenuItem jmi_cp;
    private javax.swing.JMenuItem jmi_cs;
    private javax.swing.JMenuItem jmi_ep;
    private javax.swing.JMenuItem jmi_es;
    private javax.swing.JMenuItem jmi_login;
    private javax.swing.JMenuItem jmi_mp;
    private javax.swing.JMenuItem jmi_ms;
    private javax.swing.JMenuItem jmi_signin;
    private javax.swing.JMenuItem jmi_signout;
    private javax.swing.JTextField mp_cat;
    private javax.swing.JTextField mp_dir;
    private javax.swing.JSpinner mp_h;
    private javax.swing.JTextField mp_id;
    private javax.swing.JSpinner mp_min;
    private javax.swing.JTextField mp_nom;
    private javax.swing.JTextField mp_pr;
    private javax.swing.JSpinner mp_rat;
    private javax.swing.JTextField ms_cat;
    private javax.swing.JTextField ms_dir;
    private javax.swing.JSpinner ms_h;
    private javax.swing.JTextField ms_id;
    private javax.swing.JSpinner ms_min;
    private javax.swing.JTextField ms_nom;
    private javax.swing.JTextField ms_pr;
    private javax.swing.JSpinner ms_rat;
    private javax.swing.JSpinner ms_temp;
    private javax.swing.JTextField signin_email;
    private javax.swing.JPasswordField signin_pass;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Usuario> usuarios = new ArrayList();
    private ArrayList<Serie> series = new ArrayList();
    private ArrayList<Pelicula> peliculas = new ArrayList();
    int index_u = 0;
}
